#!/usr/bin/env fish

function kube-delete-ns
    kubectl proxy &>/dev/null &
    set KUBE_PROXY_PID $last_pid
    for ns in $argv
        echo -en " Checking namespace "(set_color -o)"\033[1;34m$ns\033[1;0m"(set_color normal)
        kubectl get ns $ns &>/dev/null
        if test $status -gt 0
            echo -ne "\033[2K\033[10000D"
            set_color --italics ff3
            echo -n " i"
            set_color normal
            echo -e " Namespace \033[1;34m$ns\033[1;0m already deleted"
            continue
        end
        echo -en "\033[2K\033[10000D Deleting namespace "(set_color -o)"\033[1;34m$ns\033[1;0m"(set_color normal)" ..."
        kubectl get namespace $ns -o json | jq '.spec = {"finalizers":[]}' >/tmp/kube-ns-to-delete.json
        curl -ks \
            -o /dev/null \
            -H "Content-Type: application/json" \
            -X PUT \
            --data-binary @/tmp/kube-ns-to-delete.json \
            http://127.0.0.1:8001/api/v1/namespaces/$ns/finalize 2>&1
        # following line is doing cursor movements (https://tldp.org/HOWTO/Bash-Prompt-HOWTO/x361.html, http://ascii-table.com/ansi-escape-sequences.php, https://en.wikipedia.org/wiki/ANSI_escape_code#Terminal_output_sequences)
        echo -e "\033[2K\033[10000D \033[0;32m✔\033[0m Deleted \033[1;34m$ns\033[1;0m"
    end
    if test -e /tmp/kube-ns-to-delete.json
        rm /tmp/kube-ns-to-delete.json &>/dev/null
    end
    kill -TERM $KUBE_PROXY_PID
end

kube-delete-ns $argv
